# Generated by Django 3.1.3 on 2021-04-17 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название блюда')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('category', models.CharField(choices=[('AP', 'закуски'), ('CP', 'холодные закуски'), ('HA', 'горячие закуски'), ('ST', 'первые блюда'), ('SO', 'супы'), ('SA', 'салаты'), ('MD', 'основные блюда'), ('ME', 'блюда из мяса'), ('SE', 'стейки'), ('PD', 'блюда из птицы'), ('FS', 'морепродукты'), ('SI', 'гарниры'), ('SN', 'закуски'), ('SU', 'соусы'), ('DE', 'десерты'), ('BE', 'напитки'), ('SD', 'прохладительные напитки'), ('HD', 'горячие напитки'), ('WL', 'винная карта')], max_length=2, verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_table', models.CharField(max_length=30, unique=True, verbose_name='Table name')),
                ('is_available', models.BooleanField(default=False, help_text='If the table is free-True, busy-False', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Стол',
                'verbose_name_plural': 'Столы',
                'ordering': ['is_available'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Колличество')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Общая стоимость')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MenuItem', to='restaurant.menuitem', verbose_name='Пункт меню')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Номер заказа')),
                ('number_of_guests', models.PositiveSmallIntegerField(default=1, verbose_name='Количество гостей')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Сумма за весь заказ')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания заказа')),
                ('dish_is_ready', models.BooleanField(default=False, verbose_name='Отметка о готовности заказа на кухне')),
                ('time_dish_is_ready', models.CharField(blank=True, max_length=10, null=True, verbose_name='Время приготовления заказа')),
                ('comment', models.CharField(blank=True, max_length=250, null=True, verbose_name='Комментарий')),
                ('cancelled', models.BooleanField(default=False, verbose_name='Заказ отменен')),
                ('paid', models.BooleanField(default=False, verbose_name='Заказ оплачен')),
                ('items', models.ManyToManyField(to='restaurant.OrderItem')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.table', verbose_name='Стол')),
            ],
        ),
    ]
