# Generated by Django 3.1.7 on 2021-04-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_table', models.CharField(max_length=30, unique=True, verbose_name='Table name')),
                ('status', models.BooleanField(default=False, help_text='If the table is busy-True, free-False', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ['status'],
            },
        ),
    ]
