# Generated by Django 3.1.7 on 2021-04-11 10:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import users.models.admin
import users.models.cook
import users.models.custom_user
import users.models.waiter


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone_number', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Телефон должен быть в формате: '+375296788767'", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефонный номер')),
                ('is_waiter', models.BooleanField(default=False, verbose_name='Официант')),
                ('is_cook', models.BooleanField(default=False, verbose_name='Повар')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Администратор')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Суперюзер')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Сотрудник')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Все пользователи',
                'ordering': ['is_admin'],
            },
            managers=[
                ('objects', users.models.custom_user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin', serialize=False, to='users.customuser', verbose_name='Администратор')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=users.models.admin.upload_avatar_image_dir, verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Администратор',
                'verbose_name_plural': 'Администраторы',
            },
        ),
        migrations.CreateModel(
            name='Cook',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cook', serialize=False, to='users.customuser', verbose_name='Повар')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=users.models.cook.upload_avatar_image_dir, verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Повар',
                'verbose_name_plural': 'Повара',
            },
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='waiter', serialize=False, to='users.customuser', verbose_name='Официант')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=users.models.waiter.upload_avatar_image_dir, verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Официант',
                'verbose_name_plural': 'Официанты',
            },
        ),
    ]
