# Generated by Django 3.1.7 on 2021-04-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='cook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created by'),
        ),
    ]
